name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.config.name }} | ${{ matrix.config.build_type }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:

        - name: macOS
          os: macos-15
          extra_options: -G Xcode -DDYN_OPENAL=OFF
          build_type: Debug
    steps:
    - uses: actions/checkout@v4
    - name: Create Package
      shell: bash
      run: |
        cd build-ios.202408
        mkdir output
        xcodebuild -output build -exportArchive
        
    - name: Upload Package
      uses: actions/upload-artifact@v3
      with:
        path: build-ios.202408/build
        name: ${{ matrix.config.name }} ${{ matrix.config.build_type }}
